# Development docker-compose for local development
version: '3.8'

services:
  app:
    build:
      context: ../../..
      dockerfile: infra/docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../../src:/app/src
      - ../../../package.json:/app/package.json
      - ../../../tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    restart: unless-stopped

  # Optional: Add a database for more complete local development
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: shopping_cart
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: dev
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # Optional: Add Redis for caching/sessions
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"

# volumes:
#   postgres_data: